import os

EOS = '$$EOS$$'
UNK = '__UNK__'

DATA_PATH = 'data/filtered.json'
DESCRIPTIONS_PATH = 'data/descriptions'
OUTPUT_VOCAB_PATH = 'data/out_vocab.json'

WORD2VEC_MODEL_PATH = 'models/word2vec'
TRANSLATOR_MODEL_PATH = 'models/translator'

OUTPUT_MAX_VOCAB_SIZE = 20000

TOKEN_SIZE = 128
INPUT_SEQUENCE_LENGTH = 32
ANSWER_MAX_TOKEN_LENGTH = 8
HIDDEN_DIM = 32
INPUT_LAYER_DEPTH = 1
OUTPUT_LAYER_DEPTH = 1

TEST_PAIRS_NUM = 10
TRAIN_BATCH_SIZE = 1
TEST_FREQUENCY = 1
